name: Always Data Deploy
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Setup Go 1.22.x
      uses: actions/setup-go@v5
      with:
        # Semantic version range syntax or exact version of Go
        go-version: '1.22.x'

    - name: CGO
      run: go env -w CGO_ENABLED=0
  
    - name: Install dependencies
      run: go get .
    
    - name: Build
      run: go build

    - name: chmod
      run: chmod a+x gocroot

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.server }}
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
        exclude: |
          **/.git*
          **/.git*/**
          **/*.go*
          *.go
          **/*.git*/**